# This is file for testing work docker on sevreral systems

version: "3.9"
services:

  rabbitmq:
    build: rabbitmq/
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "user1"
      RABBITMQ_DEFAULT_PASS: "0000"
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 2s
      timeout: 2s
      retries: 1
    networks:
      my-app-net:
        ipv4_address: 10.0.0.3

  server:
    image: sr
    container_name: server
    build: server/
    command: python3 consumerSync.py -n c1 -t 100 -m confirmMannually -q queue1 -si 10.0.0.3 -u user1 -p 0000
    ports:
      - "8080:8080"
    environment:
      - HOSTNAMERABBIT=rabbitmq
    restart: on-failure
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    networks:
      - my-app-net

networks:
  my-app-net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.0.0/20
        gateway: 10.0.0.2